### PR TITLE
Fix #create_or_update_student

### PR DESCRIPTION
**Pull request by grmnlrt**
Received the following response from Edusign CTO about my question related to student duplicates:

Screenshot 2024-01-25 at 11 02 19

After investigations, I think we should always try to find a student with they uid and with they email if not found with the uid. WDYT?

### CODE REVIEW

**Comment by Eschults** [comment]
❓ @grmnlrt is the uid different for the 21 records created at the account level?

**Comment by grmnlrt** [comment]
@Eschults Yes, the uid is each time different

**Comment by Eschults** [comment]
👌

**Comment by Eschults** [comment]
Could you `bundle update edusign` in Kitt & Learn 🙏 ? 

Also it would be nice to add a `bin/release` here to fix a 🐛 we have locally when running `bundle install` w/ an old sha referenced in the `Gemfile.lock` on Kitt and Learn, let's discuss this when you have a minute 🚀

**Comment by grmnlrt** [comment]
@Eschults not sure to understand what you mean with the `bin/release` 🤔

**Comment by Eschults** [comment]
Let's write one as we did for [lewagon/linkedin-extension](https://github.com/lewagon/linkedin-extension/blob/master/bin/release) and [lewagon/kitt](https://github.com/lewagon/kitt/blob/master/bin/release) to actually create git releases and bump the version of the gem when we "publish" a set of changes merged in `master` 👌

**Pull request merged**
